### ISSUE TITLE
Open pose giving issues

### ISSUE THREAD

**Issue by ALI7861111** [chonyy/basketball-shot-detection#6]
I tried both the code in my local machine and in my google colab with gpu but got the same error

**Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
Traceback (most recent call last):
  File "detection.py", line 15, in <module>
    datum, opWrapper = openpose_init()
  File "/content/basketball-shot-detection/utils.py", line 23, in openpose_init
    raise e
  File "/content/basketball-shot-detection/utils.py", line 20, in openpose_init
    from Release import pyopenpose as op
ImportError: cannot import name 'pyopenpose'**

**Comment by chonyy** [comment]
Hi, maybe I didn't make it clear. You have to install [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) on your machine before running this project.
Luckily, this notebook could help you walk through the whole process!
[<img src="https://colab.research.google.com/assets/colab-badge.svg" align="center">](https://colab.research.google.com/github/hardik0/AI-basketball-analysis-on-google-colab/blob/master/AI_basketball_analysis_google_colab.ipynb)

**Comment by ALI7861111** [comment]
Thanks a lot . but anaconda has some type of complication with openpose in the original directory openpose build for [windows](https://github.com/CMU-Perceptual-Computing-Lab/openpose) is failing
